# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

def sharedPods
  use_frameworks!
  pod 'SnapKit'
  pod 'RxSwift'
  pod 'RxCocoa'
end

target 'FMRxSwiftDemo' do
  sharedPods
end

target 'Start' do
  sharedPods
end

target 'Start_RxSwift' do
  sharedPods
end

target 'Final_RxSwift' do
  sharedPods
end

target 'MVVM_RxSwift' do
  sharedPods
end
